---
title: "plots"
output: html_document
date: "`r Sys.Date()`"
---
# packages
```{r,message=FALSE}
library(tidyverse)
library(TRmaps)
library(esquisse)
```

```{r}
ggplot(sigorta_mv) +
 aes(x = cogunluk_parti_oran_2018, y = s_degisim17_18, colour = cogunluk_parti_2018) +
 geom_point(shape = "circle", 
 size = 1.85) +
 scale_color_manual(values = c("AK PARTİ" = "orange2", "CHP" = "red3","HDP"="purple3"
)) +
 labs(x = "Oy Oranı", y = "2017'ye Göre Kamu Personeli Artışı Oranı", title = "2018 Yılında İllere Göre Kamu Personeli Artış Oranı ve Alınan Oy Oranı ", 
 subtitle = "Veriler YSK ve SGK'den alınmıştır", color = "Çoğunluk Parti") +
 theme_bw()


ggplot(sigorta_mv) +
 aes(x = cogunluk_parti_oran_2015, y = s_degisim14_15, colour = cogunluk_parti_2015) +
 geom_point(shape = "circle", 
 size = 1.85) +
 scale_color_manual(values = c("AK PARTİ" = "orange2", "CHP" = "red3","HDP"="purple3"
))+
  labs(x = "Oy Oranı", y = "2014'e Göre Kamu Personeli Artışı Oranı", title = "2015 Yılında İllere Göre Kamu Personeli Artış Oranı ve Alınan Oy Oranı ", 
 subtitle = "Veriler YSK ve SGK'den alınmıştır", color = "Çoğunluk Parti") +
 theme_bw()+
  lims()
```

```{r}
ggplot(sigorta_mv) +
  aes(x = cogunluk_parti_oran_2018, y = s_degisim17_18) +
  geom_point(shape = "circle", size = 1.5,aes(colour = iktidar_2018))
```


# plots
```{r}
ggplot(sigorta_mv,aes(x =cogunluk_parti_oran_2018, y = s_degisim17_18))+
  geom_point(aes(color = as.factor(iktidar_2018)))+
  geom_smooth(aes(color = as.factor(iktidar_2018)),method = "lm")+
  scale_color_manual(values = c("red3","orange"))
```
# harita üzerinde çalışmalar
```{r}
tr_nuts3 <- TRmaps::tr_nuts3
tr_nuts3 <- rename(tr_nuts3,il_adi = name_tr)
tr_nuts3 <- tr_nuts3 %>% 
  arrange(il_adi)
sigorta_mv <- sigorta_mv %>% 
  arrange(il_adi)
harita <- cbind(tr_nuts3,sigorta_mv)
```


```{r}
ggplot(harita)+
  geom_sf(aes(fill = cogunluk_parti_2018))+
  theme(legend.position = "top",)+
  scale_alpha_continuous(guide = F)+
  scale_fill_manual(values = c("AK PARTİ" = "orange2", "CHP" = "red3","HDP"="purple3"))+
  labs(fill = "Çoğunluk Parti",
       alpha = "Kamu Sigortalı Çalışan Değişimi",
       caption = "Koyu renkli illerde kamu sigortalı değişimi daha fazladır")
```

